extension.js, index.js
@theRealPadster Everything look good to you?
=> Optimization

extension.js
Add recursive pagination so it loads more than one page of data.
=> Optimization dev

src/Card.js
=> Fix: Don't open readme page when clicking author name

src/Card.js, style.css, styles/components/card.scss
=> feat(Card): link title to repo link

src/components/Grid.tsx, src/logic/FetchRemotes.ts
Resolves #203 
Added types where possible
Basically #181 but now passes query through functions
Already linted using `eslint --fix src`
=> feat(Grid): port search function

resources/snippets.json, src/components/ReadmePage.tsx, src/components/TabBar.tsx, src/styles/components/_add-snippet-modal.scss
Resolves #196 
Changes derived from #229, previews are stored there
=> fix: several changes

README.md, package.json, src/components/Card/Card.tsx, src/components/Grid.tsx, src/components/Modals/Changelog/index.tsx, src/constants.ts, src/logic/FetchRemotes.ts, src/types/marketplace-types.d.ts
=> Add custom apps tab

.eslintrc.js, src/components/TabBar.tsx
Resolve type errors present in current build
=> chore: resolve type errors

.github/workflows/push.yml, package.json, packages/backend/src/server/app.ts, packages/backend/src/server/config.ts, packages/backend/src/server/controllers/indexController.ts, packages/backend/src/server/interfaces/controller.ts, packages/backend/src/server/routes/home.ts, yarn.lock
Cache `yarn` packages for new version & apply ESLint across repo
=> ci(push): cache dependencies for new `yarn` version

packages/marketplace/src/resources/snippets.ts
=> fix(snippet): correct key name

packages/marketplace/src/components/TabBar.tsx
=> chore: remove `TabBar` console log statement

resources/install.ps1
condition testing buggy as hell
=> test(install): force usage of placeholder theme

packages/marketplace/src/resources/locales/fr.json
Is it possible to add theses following texts in the `en.json` file please ?
Left side:
Right side:
Thanks.
=> Improve French translation

packages/marketplace/src/styles/components/_grid.scss
=> fix: compatibility with new Spotify layout

packages/marketplace/src/components/Card/Card.tsx, packages/marketplace/src/components/Modals/Snippet/index.tsx, packages/marketplace/src/components/Modals/ThemeDevTools/index.tsx, packages/marketplace/src/components/ReadmePage.tsx, packages/marketplace/src/extensions/extension.tsx, packages/marketplace/src/logic/FetchRemotes.ts, packages/marketplace/src/logic/Utils.ts, packages/marketplace/src/types/spicetify.d.ts
Use new error param for `showNotification`
=> Feat: error-notifications

package.json, packages/backend/package.json, packages/marketplace/package.json, yarn.lock
=> chore: bump dependencies

packages/marketplace/src/components/Grid.tsx
I forgot to do this originally 🙃
=> 🐛 Update `Spicetify.Config.color_scheme` when using dropdown

packages/marketplace/package.json, packages/marketplace/src/app.tsx, packages/marketplace/src/components/Modals/ImportExport/index.tsx, packages/marketplace/src/components/Modals/Settings/index.tsx, packages/marketplace/src/styles/components/_import-export.scss, packages/marketplace/src/styles/styles.scss
@theRealPadster Should account for everything referenced in your review
=> Cleanup import-export feature

resources/install.ps1
Fetches latest release and uses that to install instead of `dist` ref
=> feat(windows/install): use GitHub API to fetch release

.github/workflows/push.yml
=> fix(action/push): use worktree

packages/marketplace/src/resources/locales/zh-TW.json
Source-Commit: 9cdf176522125b51d9fc42ab1c067110d50bcd4b
=> i18n: Update zh_TW translation

packages/marketplace/src/resources/snippets.ts
=> fix: rotating-coverart image

README.md
=> feat(readme): add downloads badge to readme

src/components/Grid.tsx
=> fix(grid): search by author

src/components/Grid.tsx, src/logic/FetchRemotes.ts
More issues than it is actually useful
=> chore: remove API request on search `Enter`

resources/color.ini
Some of these values are a bit off from the default ones (`button` and `button-active`), plus if for some reason these values changes we would only need to commit it from the CLI without needing to do it here also
=> fix: use CLI placeholder value

resources/install.ps1
based on [Microsoft guidelines](https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/cmdlet-development-guidelines),  community [The PowerShell Best Practices and Style Guide](https://poshcode.gitbook.io/powershell-practice-and-style) and [PSScriptAnalyzer](https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer) warnings
also minor logic improvements
=> refactor(windows install): refactor posh install script

src/components/Card/Card.tsx, src/extensions/extension.tsx, src/logic/Utils.ts
Domain works for some, breaks for others, best that we use both and test them accordingly.
=> fix: use `.xyz` domain as fallback

src/styles/components/_grid.scss
=> fix(styles/grid): marketplace update icon margin

package.json, pnpm-lock.yaml
Bumps dependency version of spicetify-creator to fix issue with multiple render function declarations. 
Also bumps a couple other deps while I'm at it.
=> fix(deps): bump dependencies

.github/workflows/auto_release.yml
=> fix(workflows): auto-release

.github/ISSUE_TEMPLATE/config.yml
there is already an organization's [one](https://github.com/spicetify/.github/blob/main/.github/ISSUE_TEMPLATE/config.yml)
=> chore(issue_template): remove config

src/components/Modals/Settings/index.tsx, src/logic/Utils.ts, src/types/marketplace-types.d.ts
the reset button doesn't work right now
=> fix: reset marketplace button

.vscode/launch.json, resources/snippets.json, src/components/Grid.tsx, src/constants.ts, src/logic/FetchRemotes.ts
I tested it locally by commenting out the fetch call and importing the `snippets.json` file, since this change isn't live yet.
=> feat: fetch snippets from github repo at runtime

package.json
Since this will likely be the last release before Marketplace v2.
=> feat: bump package version to 1.0.0

resources/blacklist.json
Accordingly to https://github.com/spicetify/spicetify-marketplace/pull/742#issuecomment-2095934187
=> chore(blacklist): remove an extension

package.json, pnpm-lock.yaml, src/components/ReadmePage.tsx
Fixes clicking `Install` button when Global Navbar is enabled
=> fix(tabbar): add margin top on readme page

resources/snippets.json
=> feat(snippets): support npv ambience [ Rotating Cover Art ]

resources/snippets.json
Closes #880. Fixed resize handle positions upon switching sidebar positions. Drag to resize works in reverse / pre-switching context.
=> fix(snippet/switch-sidebars): reposition resize handle

resources/snippets.json
=> fix(snippets): smaller right sidebar cover art

src/components/Card/TagsDiv.tsx
someone's manifest has empty tags and literally no one did the check for them 🤦‍♀️
=> fix(tagsdiv): ensure there's empty array to sort

package.json, src/components/Card/TagsDiv.tsx, src/components/Modals/Settings/DnDList.tsx
The offset function is not perfect, but that's what I came up with on the spot just so the dnd-boxes follow the cursor, and not go somewhere to the right based on the mouse
fixes https://github.com/spicetify/marketplace/issues/886
=> fix(DnDList): rendering the list & add some offset

resources/snippets.json
Fix the smaller right sidebar cover art snippet.
and fixed my stupid small mistake 🙃
=> fix(snippets): smaller right sidebar covert art

resources/blacklist.json
Fork of spicy-lyrics. We do not allow forks on marketplace. Pull Requests exist.
=> feat(blacklist): add `amai-lyrics`

resources/snippets.json
=> feat(snippets): minecraft progress bar

src/resources/locales/index.ts, src/resources/locales/ko.json
I hope you can review it and include that in the language support. thank you.
=> feat(i18n): add korean translation

src/components/Button.tsx, src/components/Card/Card.tsx, src/components/Grid.tsx, src/components/Modals/Settings/ConfigRow.tsx, src/components/TabBar.tsx, src/components/Tooltip.tsx, src/styles/components/_grid.scss, src/types/spicetify.d.ts
=> fix: rewrite `TabBar` logic & lazy load tooltip
