README.md
install.ps1

Made another pull requests because of the mess I made on the other one :P
I've added a powershell script that checks if spicetify is installed or not (then installs if needed), then downloads the main branch, unzips it and places it in the correct folders. It then applies the necessary Spicetify commands and installs it. (it *should* also be able to handle updates eg: it is already installed but the script is ran again)
I also added instructions on how to use this into the README.
I have gotten a few people to test it and it seems to work now. If there are any issues with this, mention me and I will try fix any bugs I couldn't find before. I am not amazing with powershell but I gave it my best shot 😅

Added a (better) auto-install script for Windows

---

snippets.json

- `Fix playlist arrows`, fixes the opened and closed orientation of the playlist folder arrows (as well as hover state; it made more sense to me for the icons not to rotate when hovering)
- `Fix main view width`, makes main view fill up all available space. This mostly applies to larger screens and when if zoomed out. 
- `Left aligned heart icons`, moves the heart icons to the left side of the track title in track views. This applies to everywhere tracks are displayed, such as in playlists, artist pages, albums etc.

[Snippets] Fix playlist arrows, Fix main view width & Left aligned heart icons

---

index.js

- Adds search function for Marketplace (or at least finishes it), thought this was much needed
Currently compare search query with name/user and filters array
- Line 843: Unnecessary condition ig?

feat(index): add search function

---

src/components/Card/Card.tsx
src/constants.ts

Fix `href` for snippet Cards as they don't have their own repos and authors field and would return `undefined`

fix(Card): use snippet URL if card is a snippet

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/push.yml
.husky/pre-commit
package.json
src/components/Grid.tsx
src/components/TabBar.tsx
src/logic/FetchRemotes.ts
yarn.lock

Testing new changes for Lint CI, should return the following errors:

ci: change workflow runs, add Husky & resolve lint errors

---

src/components/Modals/Settings/TabRow.tsx
src/styles/components/_settings.scss

Fixed an issue where Marketplace would crash on moving tabs to non-existent index
<details>
<summary>Details</summary>
- Before:
- After:
</details>

fix(TabRow): Marketplace crashing on moving tabs

---

package.json
src/components/Grid.tsx
src/components/Modals/Changelog/index.tsx
src/components/ReadmePage.tsx
src/constants.ts
src/styles/components/_grid.scss
yarn.lock

- Feature update:
Now checks for new updates every time Marketplace is opened and notifies the user via a button that leads to the repository:
- Styling update:
Merge search bar onto header
- TODO:

feat(Grid): add update checker

---

README.md
resources/install.ps1
resources/install.sh

Workaround for the color injection problem that can be encountered when installing themes through Marketplace when no local theme is applied.
Also added the `preview` key for the Snippets part.

fix: theme color injection workaround

---

src/components/Card/TagsDiv.tsx

Fix an issue where the Card tags could duplicate when rendered in `Installed` tab
Also declared types for ease of maintenance.

fix(Card): remove duplicate tags from appearing

---

packages/marketplace/package.json

Points to correct path for `copy:docs`

fix(ci): don't copy nonexistent docs folder

---

packages/marketplace/src/logic/Utils.ts

- Omits comments that follow values in `color.ini` which returns invalid color strings.
Bug found via nimsandu/spicetify-bloom#41

fix(utils): remove comments from values

---

packages/marketplace/src/app.tsx
packages/marketplace/src/styles/components/_grid.scss

Apply `margin-left` for every element placed in Heading instead of explicitly declaring them for each element.
Fix current `margin-left` problem also.

fix(app): null check for `ReadmePage` & styling

---

packages/marketplace/src/styles/components/_grid.scss

apparently `div` was not inclusive enough

style(grid): topbar margin

---

packages/marketplace/src/components/Grid.tsx

When typing in search textbox, items in `Grid` is changed visually (except star count). But when you press install button, it installs item at position in initial list.
Example:
- Open Marketplace, Extensions tab
- Enter `copy` in search textbox
- Press Install at `Copy to Clipboard`, console log says it installed Hide Podcasts extension
https://user-images.githubusercontent.com/31266357/180731330-d2b299da-196c-425d-8fd0-2a80561cbda5.mp4
After fix:
https://user-images.githubusercontent.com/31266357/180731865-916543e3-2aba-4ae7-95d3-83b4da503f6a.mp4

fix(grid): card filter on search

---

packages/marketplace/src/components/Card/Card.tsx
packages/marketplace/src/components/Grid.tsx
packages/marketplace/src/logic/Utils.ts

Resolves #106 
~~this is part of the reason why cards refused to re-render on search lol~~ as React won't render new components if they have the same key.

fix(Grid): only re-render cards on state change

---

packages/marketplace/src/styles/components/_settings.scss

Breaks other extensions & custom apps stylings after visiting Marketplace
Marketplace CSS applied globally:

fix(settings): compatibility with other extensions

---

packages/marketplace/src/components/ReadmePage.tsx

fix(readme-page): scrollbar not showing up on image load

---

packages/marketplace/src/components/Grid.tsx

style(grid): Add space between + and “Add CSS”

---

resources/install.ps1

i hate powershell
More details in spicetify/spicetify-cli#1940

fix: handling username with special characters

---

packages/marketplace/src/components/Card/Card.tsx
packages/marketplace/src/components/Modals/Snippet/index.tsx
packages/marketplace/src/logic/LaunchModals.tsx

For the same reason we added the `Install` button inside Readme pages, plus a small number of users were reporting that they couldn't get the Install/Remove button to display when hovering over cards when there aren't any alternative ways of doing the same thing.

feat: add `Install` button in `View Snippet` modal

---

package.json
packages/marketplace/package.json
packages/marketplace/src/app.tsx
packages/marketplace/src/components/Modals/Settings/ConfigRow.tsx
packages/marketplace/src/components/Modals/Settings/index.tsx
packages/marketplace/src/constants.ts
packages/marketplace/src/extensions/extension.tsx
packages/marketplace/src/logic/Utils.ts
packages/marketplace/src/resources/locales/en-US.json
packages/marketplace/src/resources/locales/en.json
packages/marketplace/src/types/marketplace-types.d.ts
yarn.lock

Going to edit the title before we merge, just thought it'd be funny.
This code isn't as clean as it can be of course, which is what I assume the review process will help with, however it does work.
New libraries/ api's used
When the song changes, it will get the main color of the album art using **node vibrant**,
it will then generate a scheme using **thecolorapi**
and the final library used is **chroma**, in order to sort the scheme the user actively has installed by the amount of contrast between each color 
To elaborate on some things, the reason I sort the colorMap based on the relative distance between the colors is so I can get it to approximately match the order that the schemes colorapi provides are ordered in, meaning the text and the main colors should always contrast each other …

feat: Album-Art Based Color Shifting

---

src/components/Card/Card.tsx
src/components/Grid.tsx

This adds the tooltipwrapper to the theme dev tools and settings buttons. For some reason when I tried to add it to the buttons on the cards, the tooltip doesn't show up.

feat: Add TooltipWrapper to icon buttons

---

src/components/Card/Card.tsx

The icons in the header (themeDevTools, settings) don't specify a delay, so use the default. This is the only other spot where `TooltipWrapper` is used, other than the tooltips on the dynamic colour scheme question marks, which make sense to have as instant.

fix(card): make card button tooltip delay consistent with others

---

src/constants.ts

It was going to the old workspaces url before, resulting in a 404

fix: fix broken snippet card title links

---

src/components/Card/Card.tsx
src/logic/Utils.ts

This allows you to specify a category of item to reset. It still reloads the window after the operation has completed. I wasn't sure which param format would be best, so I just went with simple one operation per call for now. 
Current usage: 
```js
Marketplace.reset();
Marketplace.reset('extensions');
```
Other potential options we might consider:
```js
Marketplace.reset({
snippets: true,
});
Marketplace.reset(['theme']);
```
EDIT: We went with a rest param, like so:
```js
// Reset individual items
Marketplace.reset('theme');
Marketplace.reset('theme', 'snippets');
// Reset everything (including settings)
Marketplace.reset();
```

feat: add `category` param to `Marketplace.reset()`

---

src/components/ReadmePage.tsx

Fixes the image urls being wrong for all of the themes from the spictify-themes repo. spicetify/spicetify-themes#901

fix(readme): set img relative to readme

---

src/components/Modals/Settings/index.tsx
src/resources/locales/en.json

Adds "version" section to the bottom of settings modal. 
Also adds a few new language strings. 
I'm not sure if this UI is inherently better than just putting "v0.8.5" in the bottom corner somewhere and copying on click or something. Feel free to chime in. 
It would also be nice if we could integrate the update checker here and show a button if there's a new version.

feat: add "version" section to bottom of settings modal

---

src/components/ReadmePage.tsx

fix(readme): conflict with search page

---

resources/install.ps1

make sure that output contains only path

fix(install): get userdata path

---

resources/install.ps1

`spicetify path userdata` output is too unreliable

fix(install): get userdata path without spicetify call

---

src/extensions/extension.tsx
src/logic/Utils.ts
src/styles/components/_readme-pages.scss

The use of .xyz instead of .net bypasses blocks in Egypt and China, it seems these countries only block the most popular domain.
This does not affect users outside of these countries, i have verified this serves its intended purpose.

fix(extensions): jsdelivr use xyz domain name

---

src/resources/snippets.ts

Updated the CSS code for the circular album art snippet I wrote last year (the one that does not rotate). Edited snippets.ts with the updated code.
Here's the segment with the new code for the existing snippet:
{
"title": "Circular Album Art",
"description": "Makes the now playing album art be circular (like a vinyl) without image rotation",
"code": ".cover-art { clip-path: circle(50% at 50% 50%);}",
"preview": "resources/assets/snippets/circular-album-art.png",
},

fix(snippets): circular album art

---

resources/install.ps1

When backup is run in quiet mode, user doesn't know why the command exited with error code because it doesn't show any error message

fix(install): stop running backup quietly

---

src/components/Grid.tsx

The previous implementation was constantly re-rendering the Grid whenever a card was added, causing terrible performance. This PR aims to solve this by only redrawing once all cards are added.

refactor(Grid): move setState outside of loops to avoid unnecessary redraws

---

src/components/Grid.tsx

simple pr to return tags in search results, they are kind of pointless without this!
resolves #591

feat(grid): return tags in search results

---

src/styles/components/_grid.scss

fix(grid styles): header position and background

---

src/components/Card/Card.tsx
src/components/Grid.tsx
src/logic/Utils.ts
src/resources/locales/en.json
src/types/marketplace-types.d.ts

the "newest" and "oldest" sorting options are actually responsible for sorting by last update date, which doesn't match their names, so I renamed them to "recently updated" and "most stale" and added sorting by repository creation date

feat(grid): sort by creation date

---

resources/install.ps1

brings support for scoop/winget/etc spicetify installations, but will still work if spicetify returns error/warning with/without path - no cons

feat(install/windows): use provided userdata path

---

src/styles/components/_grid.scss

fix(styles/grid): remove `option` background recolor

---

resources/install.ps1

> fix(install/windows): test spicetify path userdata output
works as intended only with powershell 7 rn

refactor(install/windows): follow the general rules

---

src/components/Grid.tsx
src/components/Modals/Update/index.tsx

react has been updated to version 18.0.2 in spotify v1.2.26, so this code no longer works because of the [automatic batching](https://blog.appsignal.com/2022/04/13/whats-new-in-react-18.html#:~:text=Automatic%20Batching%20in%20React%2018)

fix(grid): update check with spotify v1.2.26 & update modal

---

src/components/Card/TagsDiv.tsx

idk how to make the name shorter
before:
after:

fix(components/TagsDiv): move tags to extra if their number exceeds max by 1+

---

resources/blacklist.json

This extension has alternative backend (`zotify`) that downloads music and podcasts off the spotify servers. This is a piracy. I don't mind the `spotdl` backend because it uses ytdl to download music, but the alt one is too much. I'm not going to risk anything just because of this extension

feat: add `spiceDL` to the blacklist

---

CONTRIBUTING.md

Fixing the Contributing.md links for issues and documentation. Now documentation is correctly linked and takes a user to the website docs. Issues links now take a user to issues within the marketplace repo

fix: correct issues and docs links in `CONTRIBUTING.md`

---

src/components/Grid.tsx
src/components/TabBar.tsx

Fixes TabBar and viewport on `1.2.34`

fix(components): add necessary elements for `1.2.34`

---

resources/blacklist.json

This extension uses `LyricsPlus` name and such is confusing to our users because they're greeted with modified Lyrics-Plus with some gradient background that cannot be disabled.
If the author will change the name, we can remove it from the blacklist

feat: add extension to the blacklist

---

src/components/Button.tsx

Fixes https://github.com/spicetify/marketplace/issues/782

fix: `React` is not a type

---

src/components/Toggle.tsx

Related to Issue #782 and PR #783 
One import in the Toggle.tsx module was still faulty, this PR fixes it
Based on @rxri 's fix on #783

fix: `React` is not a type (continued)

---

src/app.tsx

Fixes faulty sorting of the tabs in marketplace even if user changed order through settings
Needed for #465

fix: tabs order from localstorage parsing

---

src/app.tsx

My previous merged PR #786 contained a mistake, this PR fixes the previous mistake + the original bug (tested properly this time, sorry!)

fix: tabs order from localstorage parsing (continued)

---

src/styles/components/_dropdown.scss

Fit dropdown width to longest content instead of width of the parent
Mostly a nitpicking thing, looks kinda silly atm and even clips text in options

fix: fit dropdown width to longest content

---

resources/snippets.json

It seems that they actively dropping classes (oh, a pun!) and switching to attributes.

fix(snippets): update homepage selectors

---

src/components/Grid.tsx
src/components/Icons/LoadMoreIcon.tsx
src/components/Icons/LoadingIcon.tsx
src/styles/components/_grid.scss

Related issue: #887
The issue: The `LoadMore` and `LoadIcon` icons were rendered behind  the "SortBy" div (which is a sticky div) and the sortBy div appeared behind the first div when the search do not return elements.
Before: 
https://github.com/user-attachments/assets/4aafa21f-62c0-472d-a7a3-7200f622fb82
After:  
https://github.com/user-attachments/assets/5f2b11df-9b8f-4ac5-9dbe-9e19875c3fc7
For the Snippets tab there is still the "+ Add CSS" button overlapping but I couldnt figure out how to fix this.

fix: icons and "Sort By" div overlapping

---

resources/snippets.json

Replaces `box-shadow` with `filter: drop-shadow` to fit the clipped artwork shape in the Now Playing sidebar
Before
After

fix(snippets): make shadow fit the circular art container

---

resources/snippets.json

The NPV and Mini Player buttons were updated in 1.2.66 which made the snippets not work. This PR fixes the snippets to properly work on 1.2.66.

fix(snippets): hide npv and miniplayer in 1.2.66
